keytool -genkeypair -alias unitks -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore unit.p12 -validity 3650 -storepass %BELLINI_PROJECT_PASSWORD% -dname "CN=localhost,OU=unit,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias productionks -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore production.p12 -validity 3650 -storepass %BELLINI_PROJECT_PASSWORD% -dname "CN=localhost,OU=production,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias partiesks -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore parties.p12 -validity 3650 -storepass %BELLINI_PROJECT_PASSWORD% -dname "CN=localhost,OU=parties,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias warehouseks -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore warehouse.p12 -validity 3650 -storepass %BELLINI_PROJECT_PASSWORD% -dname "CN=localhost,OU=warehouse,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias contractorks -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore contractor.p12 -validity 3650 -storepass %BELLINI_PROJECT_PASSWORD% -dname "CN=localhost,OU=contractor,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias catalogks -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore catalog.p12 -validity 3650 -storepass %BELLINI_PROJECT_PASSWORD% -dname "CN=localhost,OU=catalog,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias optimizationks -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore optimization.p12 -validity 3650 -storepass %BELLINI_PROJECT_PASSWORD% -dname "CN=localhost,OU=optimization,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias keycloakks -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore keycloak.p12 -validity 3650 -storepass %BELLINI_PROJECT_PASSWORD% -dname "CN=localhost,OU=keycloak,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias unittruststore -keyalg RSA -keystore unittruststore.p12 -storetype PKCS12 -dname "CN=localhost,OU=cocoa_unit_truststore,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias catalogtruststore -keyalg RSA -keystore catalogtruststore.p12 -storetype PKCS12 -dname "CN=localhost,OU=cocoa_catalog_truststore,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias productiontruststore -keyalg RSA -keystore productiontruststore.p12 -storetype PKCS12 -dname "CN=localhost,OU=cocoa_production_truststore,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias optimizationtruststore -keyalg RSA -keystore optimizationtruststore.p12 -storetype PKCS12 -dname "CN=localhost,OU=cocoa_optimization_truststore,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias warehousetruststore -keyalg RSA -keystore warehousetruststore.p12 -storetype PKCS12 -dname "CN=localhost,OU=cocoa_warehouse_truststore,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias contractortruststore -keyalg RSA -keystore contractortruststore.p12 -storetype PKCS12 -dname "CN=localhost,OU=cocoa_contractor_truststore,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias partiestruststore -keyalg RSA -keystore partiestruststore.p12 -storetype PKCS12 -dname "CN=localhost,OU=cocoa_parties_truststore,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -genkeypair -alias keycloaktruststore -keyalg RSA -keystore keycloaktruststore.p12 -storetype PKCS12 -dname "CN=localhost,OU=cocoa_keycloak_truststore,O=tacchini_group,L=Firenze,ST=Toscana,C=IT"
keytool -importkeystore -srckeystore catalog.p12 -srcstoretype PKCS12 -destkeystore unittruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore unit.p12 -srcstoretype PKCS12 -destkeystore unittruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore keycloak.p12 -srcstoretype PKCS12 -destkeystore unittruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore optimization.p12 -srcstoretype PKCS12 -destkeystore unittruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore contractor.p12 -srcstoretype PKCS12 -destkeystore unittruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore parties.p12 -srcstoretype PKCS12 -destkeystore unittruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore warehouse.p12 -srcstoretype PKCS12 -destkeystore unittruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore production.p12 -srcstoretype PKCS12 -destkeystore unittruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore catalog.p12 -srcstoretype PKCS12 -destkeystore partiestruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore unit.p12 -srcstoretype PKCS12 -destkeystore partiestruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore keycloak.p12 -srcstoretype PKCS12 -destkeystore partiestruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore optimization.p12 -srcstoretype PKCS12 -destkeystore partiestruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore contractor.p12 -srcstoretype PKCS12 -destkeystore partiestruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore parties.p12 -srcstoretype PKCS12 -destkeystore partiestruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore warehouse.p12 -srcstoretype PKCS12 -destkeystore partiestruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore production.p12 -srcstoretype PKCS12 -destkeystore partiestruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore catalog.p12 -srcstoretype PKCS12 -destkeystore productiontruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore unit.p12 -srcstoretype PKCS12 -destkeystore productiontruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore keycloak.p12 -srcstoretype PKCS12 -destkeystore productiontruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore optimization.p12 -srcstoretype PKCS12 -destkeystore productiontruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore contractor.p12 -srcstoretype PKCS12 -destkeystore productiontruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore parties.p12 -srcstoretype PKCS12 -destkeystore productiontruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore warehouse.p12 -srcstoretype PKCS12 -destkeystore productiontruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore production.p12 -srcstoretype PKCS12 -destkeystore productiontruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore catalog.p12 -srcstoretype PKCS12 -destkeystore warehousetruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore unit.p12 -srcstoretype PKCS12 -destkeystore warehousetruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore keycloak.p12 -srcstoretype PKCS12 -destkeystore warehousetruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore optimization.p12 -srcstoretype PKCS12 -destkeystore warehousetruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore contractor.p12 -srcstoretype PKCS12 -destkeystore warehousetruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore parties.p12 -srcstoretype PKCS12 -destkeystore warehousetruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore warehouse.p12 -srcstoretype PKCS12 -destkeystore warehousetruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore production.p12 -srcstoretype PKCS12 -destkeystore warehousetruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore catalog.p12 -srcstoretype PKCS12 -destkeystore optimizationtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore unit.p12 -srcstoretype PKCS12 -destkeystore optimizationtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore keycloak.p12 -srcstoretype PKCS12 -destkeystore optimizationtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore optimization.p12 -srcstoretype PKCS12 -destkeystore optimizationtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore contractor.p12 -srcstoretype PKCS12 -destkeystore optimizationtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore parties.p12 -srcstoretype PKCS12 -destkeystore optimizationtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore warehouse.p12 -srcstoretype PKCS12 -destkeystore optimizationtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore production.p12 -srcstoretype PKCS12 -destkeystore optimizationtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore catalog.p12 -srcstoretype PKCS12 -destkeystore catalogtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore unit.p12 -srcstoretype PKCS12 -destkeystore catalogtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore keycloak.p12 -srcstoretype PKCS12 -destkeystore catalogtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore optimization.p12 -srcstoretype PKCS12 -destkeystore catalogtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore contractor.p12 -srcstoretype PKCS12 -destkeystore catalogtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore parties.p12 -srcstoretype PKCS12 -destkeystore catalogtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore warehouse.p12 -srcstoretype PKCS12 -destkeystore catalogtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore production.p12 -srcstoretype PKCS12 -destkeystore catalogtruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore catalog.p12 -srcstoretype PKCS12 -destkeystore contractortruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore unit.p12 -srcstoretype PKCS12 -destkeystore contractortruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore keycloak.p12 -srcstoretype PKCS12 -destkeystore contractortruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore optimization.p12 -srcstoretype PKCS12 -destkeystore contractortruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore contractor.p12 -srcstoretype PKCS12 -destkeystore contractortruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore parties.p12 -srcstoretype PKCS12 -destkeystore contractortruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore warehouse.p12 -srcstoretype PKCS12 -destkeystore contractortruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore production.p12 -srcstoretype PKCS12 -destkeystore contractortruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore catalog.p12 -srcstoretype PKCS12 -destkeystore keycloaktruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore unit.p12 -srcstoretype PKCS12 -destkeystore keycloaktruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore keycloak.p12 -srcstoretype PKCS12 -destkeystore keycloaktruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore optimization.p12 -srcstoretype PKCS12 -destkeystore keycloaktruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore contractor.p12 -srcstoretype PKCS12 -destkeystore keycloaktruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore parties.p12 -srcstoretype PKCS12 -destkeystore keycloaktruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore warehouse.p12 -srcstoretype PKCS12 -destkeystore keycloaktruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%
keytool -importkeystore -srckeystore production.p12 -srcstoretype PKCS12 -destkeystore keycloaktruststore.p12 -deststoretype PKCS12 -deststorepass %BELLINI_PROJECT_PASSWORD% -srcstorepass %BELLINI_PROJECT_PASSWORD%